config/routes.rb
Rails.application.routes.draw do
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "welcome/say_hello" => "welcome#say"
get "welcome" => "welcome#index"
root :to => "welcome#index"
#match ':controller(/:action(/:id(.:format)))', :via => :all
resources :events do

  resources :attendees, :controller => 'event_attendees'
  resource :location, :controller => 'event_locations'

  collection do
    post :bulk_delete
    post :bulk_update
  end

  member do
    get :dashboard
    post :join
    post :withdraw
  end
  end
  
  namespace :admin do
    resources :events
  end

end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :find_event

  def index
    @attendees = @event.attendees
  end

  def show
    @attendee = @event.attendees.find( params[:id] )
  end

  def new
    @attendee = @event.attendees.build
  end

  def create
    @attendee = @event.attendees.build( attendee_params )
    if @attendee.save
      redirect_to event_attendees_url(@event)
    else
      render :action => :new
    end
  end

  def edit
    @attendee = @event.attendees.find( params[:id] )
  end

  def update
    @attendee = @event.attendees.find( params[:id] )
    if @attendee.update( attendee_params )
      redirect_to event_attendees_url( @event )
    else
      render :action => :edit
    end
  end

  def destroy
    @attendee = @event.attendees.find( params[:id] )
    @attendee.destroy
    redirect_to event_attendees_url( @event )
  end

  protected

  def find_event
    @event = Event.find( params[:event_id] )
  end

  def attendee_params
    params.require(:attendee).permit(:name)
  end

end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/views/event_attendees/edit.html.erb
<%= form_for @attendee, :url => event_attendee_path(@event, @attendee), :html => { :mothod => :path } do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/event_attendees/index.html.erb
<ul>
  <% @attendees.each do |attendee| %>
  <li>
    <%= attendee.name %>
    <%= link_to 'show', event_attendee_path(@event, attendee) %>
    <%= link_to 'edit', edit_event_attendee_path(@event, attendee)%>
    <%= link_to 'destroy', event_attendee_path(@event, attendee), :method => :delete, :data => { :confirm => "Are you sure?"} %>
  </li>
  <% end %>
</ul>
<%= link_to 'new attendee', new_event_attendee_path(@event) %>
<p><%= link_to "Back to index", events_path %></p>

app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/event_attendees/show.html.erb
<p><%= @attendee.name %></p>