config/routes.rb
Rails.application.routes.draw do
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "welcome/say_hello" => "welcome#say"
get "welcome" => "welcome#index"
root :to => "welcome#index"
#match ':controller(/:action(/:id(.:format)))', :via => :all
resources :events do

  resources :attendees, :controller => 'event_attendees'
  resource :location, :controller => 'event_locations'

  collection do
    post :bulk_delete
    post :bulk_update
  end

  member do
    get :dashboard
    post :join
    post :withdraw
  end
  end
  
  namespace :admin do
    resources :events
  end

end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name, :description
  has_many :attendees, ->{ where(["created_at > ?", Time.now - 7.day]).order("id DESC") }, :dependent =>:destroy
  belongs_to :category, :optional => true
  has_one :location, :dependent =>:destroy
  has_many :event_groupships
  has_many :groups, :through => :evevt_groupships
  belongs_to :category
  # 不明以下操作放哪里
  # delegate :name, :to => :category, :prefix => true, :allow_nil => true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  before_action :authenticate
  layout "admin"


  protected

  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == "username" && password == "password"
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, :only => [ :show, :edit, :update, :destroy ]
  def index
    if params[:keyword]
      @events = Event.where( ["name like ?", "%#{params[:keyword]}%"] )
    else
      @events = Event.all
    end

    sort_by = (params[:order] == 'name' ? 'name' : 'created_at')
    @events = Event.order(sort_by).page(params[:page]).per(5)

    respond_to do |format|
      format.html
      format.xml { render :xml => @events.to_xml }
      format.json { render :json => @events.to_json }
      format.atom { @feed_title ="My event list" }
    end

  end

  def new
    @event = Event.new
  end

  def show
    @page_title = @event.name
    respond_to do |format|
      format.html { @page_title = @event.name }
      format.xml
      format.json { render :json => { id: @event.id, name: @event.name }.to_json }
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:notice] = "event was successfully updated"
      redirect_to event_url(@event)
    else
      render :action => :edit
    end
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "event was successfully created"
      redirect_to events_url
    else
      render :action => :new
    end
  end

  def destroy
    flash[:alert] = "#{ @event.name } was successfully deleted"
    @event.destroy
    redirect_to events_url
  end

  def bulk_delete
  Event.destroy_all
  redirect_to events_path
  end

  def bulk_update
  ids = Array(params[:ids])
  events = ids.map{ |i| Event.find_by_id(i) }.compact

  if params[:commit] == "Publish"
    events.each{ |event| event.update( :status => "published" ) }
  elsif params[:commit] == "Delete"
    events.each{ |event| event.destroy }
  end

  redirect_to events_url
  end

  def dashboard
    @event = Event.find(params[:id])
  end

  def join
    @event = Event.find(params[:id])
    Membership.find_or_create_by( :event => @event, :user => current_user )

    redirect_to :back
  end

  def withdraw
    @event = Event.find(params[:id])
    @membership = Membership.find_by( :event => @event, :user => current_user)
    @membership.destroy

    redirect_to :back
  end

  def event_params
    params.require(:event).permit(:name, :description, :category_id)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <ul>
    <% @event.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<ul>
<li><%= f.label :name, "Name"%>
    <%= f.text_field :name %></li>

<li><%= f.label :description, "Description" %>
    <%= f.text_area :description %></li>

<li><%= f.select :category_id, Category.all.map{ |c| [c.name, c.id] }%></li>
</ul>

app/views/events/dashboard.html.erb
<h2>Dashboard</h2>
<%= link_to 'Back to index', events_path %>

app/views/events/edit.html.erb
<%= form_for @event do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "Update" %>
<% end %>
<%= link_to 'Back to index', :controller => 'events', :action => 'index'%>

app/views/events/event.html.erb
<%= button_to "Join", join_event_path(@event) %>
<%= button_to "Withdraw", withdraw_event_path(@event) %>

app/views/events/index.html.erb
<h2>Events list</h2>

<%= form_tag events_path, :method => :get do %>
  <%= text_field_tag "keyword" %>
  <%= submit_tag "Search" %>
<% end %>

<%= form_tag bulk_update_events_path do %>
<ul>
  <% @events.each do |event| %>
  <li>
    <%= event.id %>
    <%= check_box_tag "ids[]", event.id, false %>
    <%= link_to event.name, event_path(event) %>
    <%= event.created_at %>
    <%= link_to "(XML)", event_path(event, :format => :xml) %>
    <%= link_to "(JSON)", event_path(event, :format => :json)%>
    <%= link_to "Edit", edit_event_path(event) %>
    <%= link_to "attendees", event_attendees_path(event) %>
    <%= link_to "location", event_location_path(event) %>
    <%= link_to "Dashboard", dashboard_event_path(event) %>
    <%= link_to 'Sort by Name', events_path( :order => "name") %>
    <%= link_to 'Sort by Default', events_path %>
    <%= link_to "Delete", event_path(event), :method => :delete, :data =>{ :confirm => "Are you sure?"} %>
  </li>
  <% end %>
</ul>

<%= submit_tag "Delete", :data =>{ :confirm => "Are you sure?" } %>
<%= submit_tag "Publish" %>
<%= button_to "Delete All", bulk_delete_events_path, :method => :post, :data =>{ :confirm => "Are you sure delete all?"} %>
<% end %>

<p><%= paginate @events %></p>
<p><%= link_to 'New Event', new_event_path %></p>
<p><%= link_to "Atom feed", events_path(:format => :atom)%></p>
<p><%= link_to "Admin", admin_events_path %></p>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
  <%= render :partial => 'form', :locals => { :f => f} %>
  <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<h2>Name: <%= @event.name %></h2>
<%= simple_format(@event.description) %>
<p>Category: <%= @event.category.try(:name) %></p>

<p><%= link_to 'Back to index', events_path %></p>